services:
  # mosquitto message broker
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "1884:9001" #default mqtt port for websockets
    volumes:
      - ./certificates/broker:/mosquitto/certs:rw
      - ./certificates/ca:/mosquitto/ca_certificates:rw
      - ./broker/config:/mosquitto/config:rw
      - ./broker/data:/mosquitto/data:rw
      - ./broker/log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - mqtt5-network

  # nginx client side website
  web:
    image: nginx
    container_name: web
    volumes:
      - ./client:/var/www/html
      - ./client/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates/ssl:/etc/nginx/ssl:rw
      - ./certificates/ca:/var/www/html/ca_certificates:rw
    ports:
      - "8080:80"
      - "4438:443"
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - mqtt5-network

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./Php:/var/www/html/Php
      - ./certificates/ca:/var/www/html/ca_certificates:rw
    restart: unless-stopped
    networks:
      - mqtt5-network

networks:
  mqtt5-network:
    name: mqtt5-network